### PR TITLE
Npm build

### PR DESCRIPTION
**Pull request by etsauer**
#### What is this PR About?
Converting our repo structure such that we can build the site using NPM, instead of raw hugo and asciidoctor. This will streamline our build process so that we can build a more concise pipeline.

#### How should we test or review this PR?
Follow the updated CONTRIBUTING.md guide for build steps.

#### Is there a relevant Trello card or Github issue open for this?
#46 

#### Who would you like to review this?
cc: @redhat-cop/cant-contain-this

-----

- [x] Have you followed the [contributing guidelines](https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the uncontained.io guides?

-----

**Please note: we may close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by etsauer** [comment]
@rdebeasi addressed.

**Comment by rdebeasi** [comment]
@sabre1041, @jimdillon, and @etsauer worked on this and found the following:
- asciidoctor.js doesn't expose a CLI by default
- asciidoctor-cli.js exposes a CLI, but it doesn't take the same arguments as the Ruby version of asciidoctor. Additionally, you have to do some hackery to get it onto your `PATH`.
- The line `const cmd = spawn('gem', ['install', 'asciidoctor']);` fails in a Node.js builder image.

So, here's another idea: what if we handle the asciidoc compilation in Gulp, outside of Hugo, and then pass the HTML files to Hugo? Hugo does seem to support HTML files with front matter. This feature isn't super well-documented, but the [code is here](https://github.com/gohugoio/hugo/blob/77c60a3440806067109347d04eb5368b65ea0fe8/helpers/general.go#L65), and the following worked on my local:

#### /site/content/articles/hi.html
```
---
title: Hi
date: 2017-06-10T00:24:36-04:00
draft: false
---

<h1>Hello world</h1>
<p>This is a test</p>
```

Would you mind if I gave this approach a shot? If it works, I can push it to this branch.

**Comment by etsauer** [comment]
@rdebeasi I was also thinking something along those lines. However, considering there is [work being done in hugo to support asciidoc](https://github.com/gohugoio/hugo/issues/1435#issuecomment-403267725), i feel like maybe we're trying too hard to get this build all into one thing. Would it be easier just to give up on this quest to remove the asciidoctor gem from our build path for now, until the hugo features are complete?

**Comment by rdebeasi** [comment]
From our conversation in chat, it sounds like there might be value in keeping the npm build even if we don't use asciidoctor.js. Reopening.

**Comment by rdebeasi** [comment]
This looks great to me. I'm assuming for the purposes of the PR that the Docker image includes Ruby and asciidoctor.

I'll put together a separate PR that changes the "install asciidoctor" step to something more like "check that asciidoctor is installed, and error out if not." In master, if you don't have asciidoctor and you run hugo, the build succeeds but all your pages are blank.

**Pull request merged**
