### PR TITLE
Revising our intro statement and background

### PR DESCRIPTION
**Pull request by etsauer**
#### What is this PR About?
See title

#### How should we test or review this PR?
Read the README.md

#### Is there a relevant Trello card or Github issue open for this?
n/a

#### Who would you like to review this?
cc: @redhat-cop/cant-contain-this

-----

- [x] Have you followed the [contributing guidelines](https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the uncontained.io guides?

-----

**Please note: we may close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by etsauer** [comment]
@rdebeasi @JaredBurck

**Comment by rdebeasi** [comment]
I like the first bit, but I'm not sure what an "Informational Community" is. Could we say something like... 
- "Uncontained.io is a developer community"
- "Uncontained.io is a community resource" 
- "Uncontained.io is a community of DevOps nerds"

I'm only half kidding about that last one!

**Comment by rdebeasi** [comment]
I like the first bit, but I'm not sure what an "Informational Community" is. Could we say something like... 
- "Uncontained.io is a developer community"
- "Uncontained.io is a community resource" 
- "Uncontained.io is a community of DevOps nerds"

I'm only half kidding about that last one!

**Comment by etsauer** [comment]
@sabre1041 done.

**Comment by rdebeasi** [comment]
The updated version looks good to me! Ok to merge?

**Comment by etsauer** [comment]
Yes

**Pull request merged**
