### PR TITLE
Fix for #83.

### LINKED ISSUE #83: Article date should be populated automatically from commit meta
The dates in our articles get generated by hugo when the article is first created, or manually by the author, and rarely gets updated as new updates are made to the content. We should set up a way to auto-update the date.

### PR DESCRIPTION
**Pull request by dobozysaurus**
#### What is this PR About?

resolves #83 - automatically using the lastmod date from Git when available.

#### How should we test or review this PR?

Testing is slightly involved, since I needed to make a small mod to the container image (for installing git) to make this work:

1. Build the container image using the instructions in the contributing section.
2. Run the tests using the container image built in step 1.
3. Verify by inspection that the dates associated with each article are pulling from git.

Note that before we merge this, we'll need to update the image out on quay, or tests using the image there will fail (since git isn't available on the PATH).

#### Is there a relevant Trello card or Github issue open for this?

resolves https://github.com/redhat-cop/uncontained.io/issues/83.

#### Who would you like to review this?

@etsauer, since he opened the issue.

### CODE REVIEW

**Comment by etsauer** [comment]
@dobozysaurus actually... There is one more change needed to actually make the deployment pipeline work... unforunately it uses a different container image currently.. https://github.com/redhat-cop/uncontained.io/blob/master/.openshift/files/builder-image.yml#L34

Need to add git here too.

**Comment by dobozysaurus** [comment]
@etsauer Ah ok. So, instead of 

RUN yum install -y rubygems && yum clean all && gem install asciidoctor -v 1.5.7

do

RUN yum install -y rubygems git && yum clean all && gem install asciidoctor -v 1.5.7

?

**Comment by etsauer** [comment]
@dobozysaurus correct.

**Comment by dobozysaurus** [comment]
@etsauer done.

**Pull request merged**
