### PR TITLE
Convert repo READMEs to asciidoc #77

### PR DESCRIPTION
**Pull request by huddlesj**
#### What is this PR About?
Brief explanation of the guide or document changes you have made and/or the new content you are contributing.

Converted Markdown files to ASCIIDoc using pandoc and updated associated links from other files. 

#### How should we test or review this PR?
Include any information or commands (please use code blocks) to help reviewers understand and verify your contribution.

I tested by previewing in github and searching for old .md files in other files as links with grep.

#### Is there a relevant Trello card or Github issue open for this?
Provide a link to any open Github issues or Trello cards that describe the use case or problem you are solving.

Convert repo READMEs to asciidoc #77

#### Who would you like to review this?
cc: @redhat-cop/cant-contain-this

-----

- [ ] Have you followed the [contributing guidelines](https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the uncontained.io guides?

-----

**Please note: we may close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by etsauer** [comment]
@huddlesj does pandoc allow you to choose which heading format to use? We typically use the format:

```
= Top Header
== Level 2
=== Level 3
==== etc.
```

**Comment by huddlesj** [comment]
@etsauer Files updated with ATX head format

for my notes:
for foo in `ls -1 *.md`;do pandoc --atx-headers -t asciidoc -f markdown $foo > `basename $foo .md`.adoc;done

**Comment by rdebeasi** [comment]
Awesome - thank you for making this change! Would you mind running the migration once more to pick up the latest changes? README.md, CONTRIBUTING.md, and possibly other files have changed since this PR was opened.

Thanks, and sorry for the delay!

**Comment by huddlesj** [comment]
@rdebeasi: Branch has been updated.

**Comment by rdebeasi** [comment]
I'm not seeing any changes [that merge](https://github.com/redhat-cop/uncontained.io/pull/88/commits/a57873733fdf7d8ec0896f87c44ea490565a42f2). It looks like master was merged into the branch, but the adoc files were not regenerated. Would it be possible to regenerate the adoc files based on what's currently in master? Thank you?

**Comment by huddlesj** [comment]
@rdebeasi I pulled in updates from master but I did not see any md files that needed to be reconverted. You should be clear to merge this pull request. 

Thanks,

----
Jay

**Comment by rdebeasi** [comment]
You may not have seen updates to the markdown files because in your branch, the files have been deleted. There are missing changes, though.

For example, see the readme in your branch:
> Thanks to *@contributors…n,* for lending their valuable input and
expertise leading up to the initial release, to *@drew* and *@mattw* for
coming up with the new site name, and to *@rdebeasi* for designing and
illustrating the content templates. And to Red Hat brand, marketing,
legal, and anyone missed, thank you for your time and effort to help the
uncontained.io project.

Compare this to the readme.md in master:
> Thanks to our contributors for lending their valuable input and expertise leading up to the initial release, to @drew and @mattw for coming up with the new site name, Abby Gardner for brand design, and @lwrigh and @rdebeasi for UX design. And to Red Hat brand, marketing, legal, and anyone missed, thank you for your time and effort to help the uncontained.io project.

It might be easier to branch from master, run your scripts, and then open a new PR. Thanks for looking into this!

**Comment by huddlesj** [comment]
@rdebeasi, 
    New pull request has been opened against a fresh pull and convert from the master branch.

----
@huddlesj

**Comment by etsauer** [comment]
Closing this PR, as it is now a duplicate of #112

**Pull request closed without merging**
