### PR TITLE
change the required version of hugo

### LINKED ISSUE #170: Created a new article file with error  theme/partials/search.html:3: unexpected "=" in operand
According to this[ `new article` doc](https://github.com/redhat-cop/uncontained.io/blob/master/docs/new_articles.adoc), I tried to create a new adoc file

~~~
cd ./site/
hugo new articles/my-new-article.adoc
~~~

And I got this error messages
~~~
ERROR 2019/07/31 12:41:16 Failed to add template "theme/partials/search.html" in path "/home/jooho/dev/git/uncontained.io/site/themes/uncontained.io/layouts/partials/search.html": template: theme/partials/search.html:3: unexpected "=" in operand
ERROR 2019/07/31 12:41:16 theme/partials/search.html : template: theme/partials/search.html:3: unexpected "=" in operand
/home/jooho/dev/git/uncontained.io/site/content/articles/matchbox_overview.adoc created
~~~

### PR DESCRIPTION
**Pull request by Jooho**
What is this PR About?
hugo version 0.38.0 causes an error when it tries to create a new article.

How should we test or review this PR?
none

Is there a relevant Trello card or Github issue open for this?
resolves #170

Who would you like to review this?
cc: @redhat-cop/cant-contain-this @etsauer

'''''

[V] Have you followed the
https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.md[contributing
guidelines]?
[V] Have you explained what your changes do, and why they add value to
the uncontained.io guides?
'''''

Please note: we may close your PR without comment if you do not check
the boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by Jooho** [comment]
@etsauer Please review it. I will send another PR for a new article after this is merged.

**Comment by Jooho** [comment]
@jimdillon 
You are right. 
@etsauer and I misunderstand the hugo-bin version. This issue happened because of hugo package version, not hugo-bin.
Therefore,  I think we should specify the required hugo version(0.58) somewhere in CONTRIBUTE.md. The old version(0.37) has an issue to create a new page. Moreover, this hugo version from[this url](https://github.com/redhat-cop/uncontained.io/blob/master/container-images/hugo/Dockerfile#L4) has to be updated. This image have the same issue because of hugo version.

What do you think? @jimdillon

**Comment by etsauer** [comment]
@Jooho the `hugo` image in this repo isn't in use anymore. you can actually just delete that directory. It was an experiment to see if we could get a compiled asciidoctor binary so we could eliminated our ruby runtime requirement, but it didn't make it very far.

**Comment by JaredBurck** [comment]
PR is a bit stale and out of date. Please try recommend resolution instead.  Closing issue wont fix. Please reopen or create new issue if you still are still experience this trouble. Thanks!

**Pull request closed without merging**
