### PR TITLE
Added title to the home page

### PR DESCRIPTION
**Pull request by gautamkrishnar**
#### What is this PR About?
Added title to the homepage

| Before | After |
| ----------- | ----------- |
| Screenshot 2021-01-16 at 3 40 54 PM | Screenshot 2021-01-16 at 3 40 02 PM |
#### How should we test or review this PR?
Just check the preview after building

#### Is there a relevant Trello card or Github issue open for this?
n/a

#### Who would you like to review this?
n/a

'''''

* [x] Have you followed the
[contributing
guidelines?](https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.adoc)
* [x] Have you explained what your changes do, and why they add value to
the uncontained.io guides?

'''''

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
bump

**Comment by gautamkrishnar** [comment]
yes

**Comment by etsauer** [comment]
@JaredBurck ^

**Comment by gautamkrishnar** [comment]
bump

**Comment by gautamkrishnar** [comment]
bump

**Comment by gautamkrishnar** [comment]
ping

**Pull request closed without merging**
